// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ewq6freQqLzzckS54BTmsNHT5Kzbbc0',
    appId: '1:199094548248:web:cc0d1b813ae4d27a1e506d',
    messagingSenderId: '199094548248',
    projectId: 'cac-project-blind',
    authDomain: 'cac-project-blind.firebaseapp.com',
    databaseURL: 'https://cac-project-blind-default-rtdb.firebaseio.com',
    storageBucket: 'cac-project-blind.firebasestorage.app',
    measurementId: 'G-C68QEC853R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNs8d2twYjutykm3fbDQkncRiR7cvhnyk',
    appId: '1:199094548248:android:cf71de3f51546ea41e506d',
    messagingSenderId: '199094548248',
    projectId: 'cac-project-blind',
    databaseURL: 'https://cac-project-blind-default-rtdb.firebaseio.com',
    storageBucket: 'cac-project-blind.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB68HjggKpY6SeaEoRAxhEgpMpY_bGyLao',
    appId: '1:199094548248:ios:53532414df4dbecd1e506d',
    messagingSenderId: '199094548248',
    projectId: 'cac-project-blind',
    databaseURL: 'https://cac-project-blind-default-rtdb.firebaseio.com',
    storageBucket: 'cac-project-blind.firebasestorage.app',
    iosBundleId: 'com.example.cacProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ewq6freQqLzzckS54BTmsNHT5Kzbbc0',
    appId: '1:199094548248:web:e0386bcf893a38ca1e506d',
    messagingSenderId: '199094548248',
    projectId: 'cac-project-blind',
    authDomain: 'cac-project-blind.firebaseapp.com',
    databaseURL: 'https://cac-project-blind-default-rtdb.firebaseio.com',
    storageBucket: 'cac-project-blind.firebasestorage.app',
    measurementId: 'G-1WMM1EKFVL',
  );
}
